### PR TITLE
Transition to Laravel 4.1.*

### PR DESCRIPTION
**Pull request by rmrhz**
It would be a better move for Wardrobe to transition to Laravel 4.1.*

### CODE REVIEW

**Comment by ericlbarnes** [comment]
Nice! This will also need adjustments in the wardrobe/core repo but this should be a great start.

**Comment by rmrhz** [comment]
Glad to help out man!

**Comment by borfast** [comment]
Any plans regarding this?
How can I help?

**Comment by imkane** [comment]
Just checking on the status of it?  Wardrode is great, but without 4.1 support it's becoming useless...I was forced to upgrade to 4.1 for some other packages.

**Comment by rmrhz** [comment]
I will help if I manage to free some time.

**Comment by ericlbarnes** [comment]
I should be able to get this merged over the weekend. I want to make sure it's a smooth upgrade progress for those aren't very comfortable with composer. — Eric Barnes

**Comment by ericlbarnes** [comment]
We have an open pull request here: https://github.com/wardrobecms/core/pull/83 

That is supposed to fix the login issue on 4.1. 
— Eric Barnes

**Comment by rmrhz** [comment]
@ericbarnes are there things to be updated in the core? I could help in brushing things up

**Comment by imkane** [comment]
Any luck with this?

**Pull request merged**
